apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: application-api-rdx4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: application-api-rdx4
    app.kubernetes.io/part-of: soup
  name: application-api-rdx4
  namespace: ralphjbean-tenant
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: application-api-rdx4
    weight: 100
status: {}
