apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: application-service-gqoy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: application-service-gqoy
    app.kubernetes.io/part-of: soup
  name: application-service-gqoy
  namespace: ralphjbean-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: application-service-gqoy
status:
  loadBalancer: {}
