apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: release-service-21pw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: release-service-21pw
    app.kubernetes.io/part-of: soup
  name: release-service-21pw
  namespace: ralphjbean-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: release-service-21pw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: release-service-21pw
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:86c5fe6df0a8d727b8b677ef2a10478b804dda01129ebc15fd73b7bd8c06adf8
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
