apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: release-service-21pw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: release-service-21pw
    app.kubernetes.io/part-of: soup
  name: release-service-21pw
  namespace: ralphjbean-tenant
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: release-service-21pw
    weight: 100
status: {}
