apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: managed-gitops-jd4d
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: managed-gitops-jd4d
    app.kubernetes.io/part-of: soup
  name: managed-gitops-jd4d
  namespace: ralphjbean-tenant
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: managed-gitops-jd4d
    weight: 100
status: {}
