apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: managed-gitops-jd4d
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: managed-gitops-jd4d
    app.kubernetes.io/part-of: soup
  name: managed-gitops-jd4d
  namespace: ralphjbean-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: managed-gitops-jd4d
status:
  loadBalancer: {}
