apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: application-service-gqoy
  namespace: ralphjbean-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:ralphjbean-tenant-application-service-gqoy
        name: container-image
        resources: {}
status: {}
